
spring.application.name=SafeClutchApplication
server.port= 8081
springdoc.api-docs.path = /safeclutchapplication
spring.datasource.url=jdbc:postgresql://safeclutch.c11hunv2feip.eu-central-1.rds.amazonaws.com:5432/safeclutch
spring.datasource.username=postgres
spring.datasource.password=vaibhav123

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.main.allow-circular-references=true

## Hibernate Logging
logging.level.org.hibernate.SQL= DEBUG

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=10MB
# Max Request Size
spring.servlet.multipart.max-request-size=20MB
